services:
  mysql:
    image: mysql:8.0
    container_name: post-collector-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: post_collector
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306" # 3306 in local → 3306 in container
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: